# Generated by Django 3.0.14 on 2021-06-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feauture_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
